#!/bin/sh

echo "Hello World!"

mount -t proc none /proc
mount -t sysfs none /sys
mount -t debugfs none /sys/kernel/debug
mount -t devtmpfs none /dev
mount -t tmpfs -o size=100M,mode=1777 tmpfs /tmp

exec /bin/sh

